### ISSUE TITLE
Modal windows need to be able to have actions on their buttons.

### ISSUE THREAD

**Issue by bostonbell** [AustinRF2918/Sagebow#2]
For the setup application, the modal window itself can't redirect us to the login, this is a little bit unergonomic.

**Comment by ferm10n** [comment]
window.location.href = "/login" ?

**Comment by bostonbell** [comment]
Yeah, I've got it so you can pass in a function as a parameter to choose what function is ran when the button is pressed on the modal window, in the case that I need more than one button (which isn't necessary right now) I'll have to modify it a bit.
